{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core-keeper.serviceAccountName" . }}
  labels:
    {{- include "core-keeper.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "core-keeper.serviceAccountName" . }}
  labels:
    {{- include "core-keeper.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "" ]
    verbs: [ "" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "core-keeper.serviceAccountName" . }}
  labels:
    {{- include "core-keeper.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "core-keeper.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "core-keeper.serviceAccountName" . }}
{{- end }}
