{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "core-keeper.fullname" . }}
  labels:
    {{- include "core-keeper.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "core-keeper.fullname" . }}
  updatePolicy:
    updateMode: "Off"
{{- end }}
